# action.yml
name: 'Rooting Guide Image'
description: 'Runs the rooting guide'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ env.HOST }}
    - ${{ env.DATABASE }}
    - ${{ env.DB_USER }}
    - ${{ env.PASSWORD }}
    - ${{ env.PORT }}
