name: run-rooting-guide
on: [pull_request, workflow_dispatch]
jobs:
  rooting-guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Rooting Guide
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          database: ${{ secrets.DATABASE }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          favorite_team: "replace me"
          team_one: "replace me"
          team_two: "replace me"
