name: run-rooting-guide
on: [push]
jobs:
  rooting-guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rooting guide action
        uses: ./ # Uses an action in the root directory
